# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0002_auto_20160827_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='papers',
            name='id',
        ),
        migrations.AddField(
            model_name='papers',
            name='pname',
            field=models.CharField(default=None, max_length=50, primary_key=True, serialize=False),
        ),
    ]
