# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0003_auto_20160827_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='confimages',
            field=models.ManyToManyField(blank=True, null=True, to='conference.Images'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='confpapers',
            field=models.ManyToManyField(blank=True, null=True, to='conference.Papers'),
        ),
    ]
