# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 21:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0004_auto_20160827_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='confimages',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='confpapers',
        ),
        migrations.AddField(
            model_name='images',
            name='conference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='conference.Conference'),
        ),
        migrations.AddField(
            model_name='papers',
            name='conference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='conference.Conference'),
        ),
    ]
