# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 23:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0005_auto_20160827_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagename', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=400)),
                ('ispublished', models.BooleanField(default=True)),
                ('conference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='conference.Conference')),
            ],
        ),
    ]
