# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0007_page_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='papers',
            name='aprooved',
            field=models.BooleanField(default=False),
        ),
    ]
