# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 09:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picFile', models.FileField(default=None, null=True, upload_to='documents')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('usertype', models.CharField(max_length=50)),
                ('contactNo', models.CharField(max_length=20)),
                ('pic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userlogin.ProfilePic')),
            ],
        ),
    ]
