# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 12:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pic',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='userlogin.ProfilePic'),
        ),
    ]
