# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0008_papers_aprooved'),
        ('userlogin', '0002_auto_20160827_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='regconf',
            field=models.ManyToManyField(blank=True, to='conference.Conference'),
        ),
    ]
